import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  ArrayUnique,
  IsArray,
  IsBoolean,
  IsEmail,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  Matches,
  MaxLength
} from 'class-validator';

const timePattern = /^([01]\d|2[0-3]):[0-5]\d$/;

export class CreateRestaurantDto {
  @ApiProperty()
  @IsUUID()
  hospitalId!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  locationId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  storeId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  kitchenId?: string;

  @ApiPropertyOptional({ description: 'Kitchens mapped to this restaurant.', type: [String] })
  @IsArray()
  @ArrayUnique()
  @IsOptional()
  @IsUUID('4', { each: true })
  kitchenIds?: string[];

  @ApiProperty({ example: 'Main Cafeteria' })
  @IsNotEmpty()
  @IsString()
  @MaxLength(255)
  restaurantName!: string;

  @ApiPropertyOptional({
    description: 'Generated by the service for new restaurants. Existing values remain supported.',
    example: 'RST0001'
  })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  restaurantCode?: string;

  @ApiPropertyOptional({ example: 'cafeteria@max.local' })
  @IsEmail()
  @IsOptional()
  @MaxLength(255)
  email?: string;

  @ApiPropertyOptional({ example: '9999999999' })
  @IsOptional()
  @IsString()
  @MaxLength(30)
  mobile?: string;

  @ApiPropertyOptional({ example: 'https://example.com/thumbnail.jpg' })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  thumbnailUrl?: string;

  @ApiPropertyOptional({ example: 'https://example.com/cover.jpg' })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  coverImageUrl?: string;

  @ApiPropertyOptional({ example: 'GST123456' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  gstNumber?: string;

  @ApiPropertyOptional({ example: 'ABCDE1234F' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  panNumber?: string;

  @ApiPropertyOptional({ example: 'FSSAI123456' })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  fssaiNumber?: string;

  @ApiPropertyOptional({ example: '12345678901234, 98765432109876' })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  fssaiNumbers?: string;

  @ApiPropertyOptional({ example: 'Max Healthcare Cafeteria Unit' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  legalName?: string;

  @ApiPropertyOptional({ example: 'Ground Floor, Main Building' })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  gstAddress?: string;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isRegisteredInGst?: boolean;

  @ApiPropertyOptional({ example: 'Ground Floor' })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  address?: string;

  @ApiPropertyOptional({ example: '07:00' })
  @IsOptional()
  @Matches(timePattern, { message: 'openingTime must use HH:mm format.' })
  openingTime?: string;

  @ApiPropertyOptional({ example: '23:00' })
  @IsOptional()
  @Matches(timePattern, { message: 'closingTime must use HH:mm format.' })
  closingTime?: string;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  normalDiscountApplicable?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  staffDiscountApplicable?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  onlineOrderingEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  inRoomDiningEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  b2cQrEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  offline?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isOffline?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  open24x7?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isOpen24x7?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  vegOnly?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isVegOnly?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  takeaway?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isTakeawayEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  delivery?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isDeliveryEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  homeDelivery?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isHomeDeliveryEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  atTableDining?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isAtTableDiningEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  inRoomDining?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isInRoomDiningEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  inCarDining?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isInCarDiningEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  posOrders?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isPosOrdersEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  onlineOrders?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isOnlineOrdersEnabled?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  inventory?: boolean;

  @ApiPropertyOptional({ default: false })
  @IsBoolean()
  @IsOptional()
  isInventoryEnabled?: boolean;

  @ApiPropertyOptional({ example: 'MAX CAFETERIA' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  qrUnitName?: string;

  @ApiPropertyOptional({ example: 'MAX CAFETERIA' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  unitNameForQr?: string;

  @ApiPropertyOptional({ example: 'max@upi' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  upiId?: string;

  @ApiPropertyOptional({ example: 'HDFC Bank' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  bankName?: string;

  @ApiPropertyOptional({ example: 'HDFC Bank - Saket' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  bankNameBranch?: string;

  @ApiPropertyOptional({ example: 'Saket' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  bankBranch?: string;

  @ApiPropertyOptional({ example: 'HDFC0001234' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  ifscCode?: string;

  @ApiPropertyOptional({ example: '123456789012' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  accountNumber?: string;

  @ApiPropertyOptional({ example: 'SODEXO-MID-001' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  sodexoMid?: string;

  @ApiPropertyOptional({ example: 'SODEXO-TID-001' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  sodexoTid?: string;

  @ApiPropertyOptional({ example: 'BU001' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  sunBu?: string;

  @ApiPropertyOptional({ example: 'T1' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  sunT1?: string;

  @ApiPropertyOptional({ example: 'T2' })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  sunT2?: string;

  @ApiPropertyOptional({ default: true })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;
}
